# Generated by Django 3.1.4 on 2020-12-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='number',
        ),
    ]
