# Generated by Django 3.1.4 on 2020-12-09 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_submission_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='student',
            field=models.ManyToManyField(related_name='section_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
